CREATE PROCEDURE [dbo].[spCrearUsuario]
    @p_USR_NOMBRE NVARCHAR(100),
    @p_USR_APELLIDO NVARCHAR(100),
    @p_USR_EMAIL NVARCHAR(100),
    @p_USR_UID NVARCHAR(100),
    @p_USR_DIRECCION NVARCHAR(100),
    @p_USR_TELEFONO NVARCHAR(100),
	@p_USR_ALTURA NVARCHAR(100),
	@p_USR_CIUDAD NVARCHAR(100),
	@p_USR_PROVINCIA NVARCHAR(100)
AS
BEGIN
	DECLARE @v_USR_ROLID INT;
    SET NOCOUNT ON;
	SELECT @v_USR_ROLID = ROL_ID FROM [desarmadero].[dbo].[Roles] WHERE ROL_NOMBRE = 'Cliente';
    INSERT INTO [desarmadero].[dbo].[Usuarios] (USR_NOMBRE, USR_APELLIDO, USR_EMAIL, USR_UID, USR_DIRECCION, USR_TELEFONO, USR_ROL, USR_ALTURA, USR_CIUDAD, USR_PROVINCIA)
    VALUES (@p_USR_NOMBRE, @p_USR_APELLIDO, @p_USR_EMAIL, @p_USR_UID, @p_USR_DIRECCION, @p_USR_TELEFONO, @v_USR_ROLID, @p_USR_ALTURA, @p_USR_CIUDAD, @p_USR_PROVINCIA);

    IF @@ROWCOUNT = 0
         RETURN 0;
    ELSE
         RETURN 1;
END