CREATE PROCEDURE [dbo].[spCrearMotor]
    @NOMBRE NVARCHAR(100),
    @DESCRIPCION NVARCHAR(255),
    @PRECIO DECIMAL(18,2),
    @STOCK INT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        INSERT INTO Motores (NOMBRE, DESCRIPCION, PRECIO, STOCK)
        VALUES (@NOMBRE, @DESCRIPCION, @PRECIO, @STOCK);

        IF @@ROWCOUNT > 0
            RETURN 1;
        ELSE
            RETURN 0;
    END TRY
    BEGIN CATCH
        RETURN 0;
    END CATCH
END;