CREATE TABLE Especificaciones (
	ESP_ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	ESP_TIPO NVARCHAR(100) NOT NULL,
	ESP_CANTIDAD INT NOT NULL,
	ESP_PRECIO DECIMAL(18, 2) NOT NULL
);

CREATE TABLE Planes (
	PLA_ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	PLA_TITULO NVARCHAR(MAX) NOT NULL,
	PLA_DESCRIPCION NVARCHAR(MAX) NOT NULL,
	PLA_CANTIDADMEMORIA INT NOT NULL,
	PLA_CANTIDADDISCO INT NOT NULL,
	PLA_CANTIDADCORES INT NOT NULL,
);

CREATE TABLE Adicionales (
	ADI_ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	ADI_TIPO NVARCHAR(MAX) NOT NULL,
	ADI_PRECIO DECIMAL(18, 2) NOT NULL,
	ADI_DURACION INT NOT NULL
);

CREATE TABLE Funciones (
	FUN_ID INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	FUN_ENDPOINT NVARCHAR(50) NOT NULL, 
);

CREATE TABLE Roles (
	ROL_ID INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	ROL_NOMBRE NVARCHAR(50) NOT NULL,
);

CREATE TABLE RolesFunciones (
    ROL_ID INT NOT NULL,
    FUN_ID INT NOT NULL,
    PRIMARY KEY (ROL_ID, FUN_ID),
    FOREIGN KEY (ROL_ID) REFERENCES Roles(ROL_ID),
    FOREIGN KEY (FUN_ID) REFERENCES Funciones(FUN_ID)
);

CREATE TABLE Usuarios (
    USR_ID INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	USR_UID NVARCHAR(100) NOT NULL,
    USR_NOMBRE NVARCHAR(50) NOT NULL,
    USR_APELLIDO NVARCHAR(50) NOT NULL,
    USR_EMAIL NVARCHAR(100) NOT NULL UNIQUE,
	USR_ROL INT NOT NULL,
    USR_TELEFONO NVARCHAR(20),
    USR_CIUDAD NVARCHAR(50),
    USR_PROVINCIA NVARCHAR(50),
    USR_DIRECCION NVARCHAR(100),
    USR_ALTURA NVARCHAR(10),
	USR_ACTIVO BIT DEFAULT 0,
	FOREIGN KEY (USR_ROL) REFERENCES Roles(ROL_ID)
);

CREATE TABLE Pagos (
	PAG_ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	PAG_MERCADOPAGO_ID INT NULL,
	PAG_USER_ID INT NOT NULL,
	PAG_TOTAL DECIMAL(18, 2) NOT NULL,
	PAG_FECHA DATETIME DEFAULT GETDATE(),
	PAG_ESTADO NVARCHAR(100) NOT NULL,
	FOREIGN KEY (PAG_USER_ID) REFERENCES Usuarios(USR_ID)
);

CREATE TABLE DetallePago (
	DET_ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	DET_PAGO_ID INT NOT NULL,
	DET_ESP_ID INT NULL,
	DET_ESP_CANTIDAD INT NULL,
	DET_ADI_ID INT NULL,
	DET_ADI_CANTIDAD INT NULL,
	FOREIGN KEY (DET_PAGO_ID) REFERENCES Pagos(PAG_ID),
	FOREIGN KEY (DET_ESP_ID) REFERENCES Especificaciones(ESP_ID),
	FOREIGN KEY (DET_ADI_ID) REFERENCES Adicionales(ADI_ID)
);

ALTER TABLE DetallePago
  ADD CONSTRAINT CK_DetallePago_UnoSoloDetalle
  CHECK (
    (DET_ESP_ID IS NOT NULL    AND DET_ADI_ID  IS NULL)
    OR
    (DET_ESP_ID IS NULL        AND DET_ADI_ID  IS NOT NULL)
);

CREATE TYPE dbo.tvp_DetallePago AS TABLE (
  DET_ESP_ID INT,
  DET_ESP_CANTIDAD INT,
  DET_ADI_ID INT,
  DET_ADI_CANTIDAD INT
);